class Foodsvilla
{
	public static void main (String [] args)
	{
		String [] foods = {"gobiManchuri","chickenRoll","vegRoll","mughlaiBiryani","butterGarlicNan","panjiri","basundi","alooGobi","bhakri","pitha","muthia",
		"mutterPaneer","uttapam","phirni","meduVada","curdRice","alooParatha","shrikand","kajuKatli","punjabiKadhi","jeeraRice","avial","coconutChutney",
		"paneerTikka","kulcha","mudrasCurry","dhokla","kachori","aluchyaWadya","mysorePak","gajarKaHalwa","malaiKofta","saagPaneer","kadaiPaneer","jalebi",
		"laalMaas","falooda","choleBahature","misalPav","bhelPuri","modak","rajma","rasam","nihari","bonda","papadum","raita","laddu","jalfrezi","putuMayam",
		"puri","khaja","barfi","roganJosh","kadhi","rasMalai","dalTadka","rasgulla","shahiPaneer","misal","kulfi","pakora","panipuri","keema","pulao",
		"dalMakhani","pavBhaji","pongal","masalaDosa","palakPaneer","chicken65","pulihora","gulabJamun","chaat","appam","samosa","upma","vindaloo","khichdi",
		"hyderabadiBiryani","sambar","vadapav","chanaMasala","kheer","idli","chapati","paratha","dosa","tikka","korma","tandooriChicken","tandoori",
		"butterChicken","dal","biryani","roti","girmit","eggRice","noodles","dumBiriyani"};
		
		System.out.println(foods[0]);
		System.out.println(foods[1]);
		System.out.println(foods[2]);
		System.out.println(foods[3]);
		System.out.println(foods[4]);
		System.out.println(foods[5]);
		System.out.println(foods[6]);
		System.out.println(foods[7]);
		System.out.println(foods[8]);
		System.out.println(foods[9]);
		System.out.println(foods[10]);
		System.out.println(foods[11]);
		System.out.println(foods[12]);
		System.out.println(foods[13]);
		System.out.println(foods[14]);
		System.out.println(foods[15]);
		System.out.println(foods[16]);
		System.out.println(foods[17]);
		System.out.println(foods[18]);
		System.out.println(foods[19]);
		System.out.println(foods[20]);
		System.out.println(foods[21]);
		System.out.println(foods[22]);
		System.out.println(foods[23]);
		System.out.println(foods[24]);
		System.out.println(foods[25]);
		System.out.println(foods[26]);
		System.out.println(foods[27]);
		System.out.println(foods[28]);
		System.out.println(foods[29]);
		System.out.println(foods[30]);
		System.out.println(foods[31]);
		System.out.println(foods[32]);
		System.out.println(foods[33]);
		System.out.println(foods[34]);
		System.out.println(foods[35]);
		System.out.println(foods[36]);
		System.out.println(foods[37]);
		System.out.println(foods[38]);
		System.out.println(foods[39]);
		System.out.println(foods[40]);
		System.out.println(foods[41]);
		System.out.println(foods[42]);
		System.out.println(foods[43]);
		System.out.println(foods[44]);
		System.out.println(foods[45]);
		System.out.println(foods[46]);
		System.out.println(foods[47]);
		System.out.println(foods[48]);
		System.out.println(foods[49]);
		System.out.println(foods[50]);
		System.out.println(foods[51]);
		System.out.println(foods[52]);
		System.out.println(foods[53]);
		System.out.println(foods[54]);
		System.out.println(foods[55]);
		System.out.println(foods[56]);
		System.out.println(foods[57]);
		System.out.println(foods[58]);
		System.out.println(foods[59]);
		System.out.println(foods[60]);
		System.out.println(foods[61]);
		System.out.println(foods[62]);
		System.out.println(foods[63]);
		System.out.println(foods[64]);
		System.out.println(foods[65]);
		System.out.println(foods[66]);
		System.out.println(foods[67]);
		System.out.println(foods[68]);
		System.out.println(foods[69]);
		System.out.println(foods[70]);
		System.out.println(foods[71]);
		System.out.println(foods[72]);
		System.out.println(foods[73]);
		System.out.println(foods[74]);
		System.out.println(foods[75]);
		System.out.println(foods[76]);
		System.out.println(foods[77]);
		System.out.println(foods[78]);
		System.out.println(foods[79]);
		System.out.println(foods[80]);
		System.out.println(foods[81]);
		System.out.println(foods[82]);
		System.out.println(foods[83]);
		System.out.println(foods[84]);
		System.out.println(foods[85]);
		System.out.println(foods[86]);
		System.out.println(foods[87]);
		System.out.println(foods[88]);
		System.out.println(foods[89]);
		System.out.println(foods[90]);
		System.out.println(foods[91]);
		System.out.println(foods[92]);
		System.out.println(foods[93]);
		System.out.println(foods[94]);
		System.out.println(foods[95]);
		System.out.println(foods[96]);
		System.out.println(foods[97]);
		System.out.println(foods[98]);
		System.out.println(foods[99]);
			
	}

}